[Settings]
;Path where the driver will be installed
InstallPath=C:\Drivers
;Name of the service used by the hypervisor.
ServiceName=denuvo
;GameSettings Name of "GAME".exe
Games=MafiaTheOldCountry.exe,b1-Win64-Shipping.exe,DOOMTheDarkAges.exe
;Launch parameters for "GAME".exe
;LaunchArgs=+com_skipIntroVideo 1